separator=false
separator_block_width=5
border_top=0
border_left=0
border_right=0
border_bottom=2

[audio]
command=$HOME/.i3/i3blocks.py
interval=1
border=#476aa4
# markup=pango
signal=3

[wireless]
command=$HOME/.i3/i3blocks.py
interval=2
border=#4293a6

[cpu]
command=$HOME/.i3/i3blocks.py
interval=1
border=#d7625d

[temperature]
command=$HOME/.i3/i3blocks.py
interval=4
border=#e5a259

[battery]
command=$HOME/.i3/i3blocks.py
interval=2
signal=1
border=#b976a8

[volume]
command=$HOME/.i3/i3blocks.py
interval=5
signal=1
border=#49a658

[brightness]
command=$HOME/.i3/i3blocks.py
interval=10
signal=2
border=#d5b953

[time]
command=$HOME/.i3/i3blocks.py
interval=1
border=#d7d7d7

[lock]
command=$HOME/.i3/i3blocks.py
interval=1
border=#b3b3b3
