separator=false
separator_block_width=5
border_top=0
border_left=0
border_right=0
border_bottom=2

[wireless]
label=  
command=[[ -z "$(iwgetid -r)" ]] || echo "  $(iwgetid -r) "
interval=2
border=#4293a6

[battery]
command=$HOME/.i3/i3blocks.py get_battery
interval=2
signal=1
border=#b976a8

[volume]
command=$HOME/.i3/i3blocks.py get_volume
interval=5
signal=1
border=#49a658

[brightness]
label=  
command=printf "  %.0f " $(xbacklight -get)
interval=10
signal=2
border=#d5b953

[time]
label=  
command=echo "  $(date -R) "
interval=1
border=#d7d7d7
