theme = "solarized-dark"
[icons]
name = "awesome"
[icons.overrides]
cpu = "\uf2db"
memory_mem = "\uf538"

[[block]]
block = "custom"
command = ''' mullvad status | grep -oF "Connecting
Connected
Disconnected
Blocked" '''
shell = "sh"
interval = 5

[[block]]
block = "custom"
command = ''' mullvad relay get | sed "s/.*country \([a-z]*\).*/\1/" '''
shell = "sh"
interval = 5

[[block]]
block = "net"
format = "{ssid} {signal_strength} {speed_down;K*b} {speed_up;K*b}"
interval = 1
hide_inactive = true
[block.theme_overrides]
idle_bg = "#859900"
idle_fg = "#073642"

[[block]]
block = "backlight"
invert_icons = true

[[block]]
block = "hueshift"
hue_shifter = "redshift"
step = 50
click_temp = 3500
[block.theme_overrides]
idle_bg = "#cb4b16"
idle_fg = "#073642"

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization}"

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {available}"

# [[block]]
# block = "temperature"

[[block]]
block = "memory"
format_mem = "{mem_avail_percents}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "sound"

[[block]]
block = "time"
format = "%A, %e %B %R"
